### ISSUE TITLE
Runtime Template Class Not Working

### ISSUE THREAD

**Issue by silenuz** [mono/t4#158]
Not sure it matters but I am using Net Core 6 and am on Linux.

IDE is Jetbrains' Rider (latest)

So I'm trying to follow things in the Readme - 

> https://github.com/mono/t4/blob/main/dotnet-t4/readme.md

I copied the template file in the example and ran the command line, and the markdown file was generated correctly.
So I execute the next step:

`t4 powers.tt -c MyApp.Powers`

This appears to generate the class correctly until I try to use it.

When I add the code from the next step to a console app to try and compile in the class I get two compile errors.

`string powersTableMarkdown = new MyApp.Powers { Max = 10 }.Process();`

The first error is that Max cannot be assigned to as it contains no setter , or is inaccessible.

The second is that it cannot resolve the symbol `Process`

I managed to get it to work by adding a Setter for Max, and changing the call to `Process` to instead be `TransformText`

Am I doing something wrong?

**Comment by mhutch** [comment]
Ah, this is an error in the README. That property is not public and [can only be set](https://learn.microsoft.com/en-us/visualstudio/modeling/t4-parameter-directive?view=vs-2022#passing-values-to-a-run-time-preprocessed-text-template) via the `Session` or the `Host`.

You would have to set the Max property on the session, then call `Initialize()` to map the session values into the parameters:

```csharp
var template = new MyApp.Powers {
    Session = new Dictionary<string, object> {
        { "Max", 10 }
    }
};
template.Initialize();
string powersTableMarkdown = template.TransformText();
```

Or define a `Max` property in the template, instead of using a parameter directive:

```t4
<#@ output extension=".md" #>
<#@ import namespace="System.Linq" #>
# Table of Powers
Number | Square | Cube
--- | ---
<# foreach(int i in Enumerable.Range(2,Max)) {#>
<#= i #> | <#= i*i #> | <#= i*i*i #>
<#}#>
<#+ public int Max { get; set; } #>
```

I honestly had forgotten this weirdness in the T4 API myself, hence the incorrect docs.

I've fixed the README.md, but I'll add a new issue to fix the underlying problem. Maybe making the generated parameter property public is enough, but the template lifecycle and state mutability is a mess IMO and I'd love to have a more modern API.
