### ISSUE TITLE
Improvements request

### ISSUE THREAD

**Issue by heaths** [mono/t4#8]
With the Microsoft T4 engine not on NuGet, a lot of project templates are made more difficult because of insufficient or overly specific (e.g. XDT) transforms. But a lot of projects need it. I often write PowerShell cmdlets where the module manifest (.psd1 file) benefits from transforms such as short commit ID or version.

I would like to offer help improving this one and wondering if you'd accept changes to put this in line with modern projects' needs. This project is a great start and alternative to Microsoft T4.

- [ ] Change to use Roslyn compilation (dup of issue #6).
- [ ] Change to dotnet toolset and target net45 or netstandard1.1 (or whatever is required) for broad support.
- [ ] Build nupkg similar to the official T4 MSBuild support to support transformations during build.

**Comment by atifaziz** [comment]
> I would like to offer help improving this one and wondering if you'd accept changes to put this in line with modern projects' needs

@heaths I'd be interested in helping move this forward too. I've managed to port the project and have it building and running as a .NET Core 2.0 App, with code generation working. I've also done a spike with Roslyn integrated and while I'd love to discuss and submit a PR, I fear that I'll be falling on deaf ears given that you and @gyorgygulyas haven't gotten any response. Would you be willing to collaborate meanwhile on a fork until perhaps @mhutch gets a chance to catch her breath? The work can eventually make its way in here should it make sense.

I've submitted the trivial PR #9 to see if this thing's even on. If that gets merged then I know there's life and hope here. 😄

**Comment by mhutch** [comment]
Sorry I haven't had much time to review & merge contributions recently.

I would definitely be happy to have this functionality as part of the project. Just need to get a CLA bot set up before I can start merging stuff.

**Comment by atifaziz** [comment]
> I would definitely be happy to have this functionality as part of the project.

@mhutch That's good to hear. Meanwhile, this weekend I went ahead and worked on a [fork called T5](https://github.com/atifaziz/t5). It's working on .NET Core 2.0 using Roslyn's C# scripting to compile and run the generator. It's working perfectly against the some simple templates (see [`Fold.g.tt`][Fold.g.tt] and [`ToDelimitedString.g.tt`][ToDelimitedString.g.tt] from the [MoreLINQ][morelinq] project). I have also cleaned-up/simplified the project organisation, added build scripts for Windows & Linux, including CI on AppVeyor & Travis. The TextTransform assembly is also setup to run via [`dotnet` CLI extensibility](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility). I am almost at the point of pushing out a v1.0, or at least a beta pending some documentation.

The main reasons I went with a separately named fork are:

- I didn't want to conflict with the identity of this project in case I needed to publish something before things picked up here.
- I didn't know the roadmap of this project as it seemed quiet here.
- I wasn't up to taking on the burden of maintaining a version working across .NET Framework on the desktop, Mono and .NET Core.

My goal was to get it on .NET Core and look forward, especially because, presumably, many details would have to be different (especially assembly references) and I am not sure x-plat templates is a possibility or even an interesting problem to solve. That all said, I am one who is against a single-weekend sprint (or hero efforts although T5 hardly qualifies as one) only to abandon the project downstream when one gets busy with other chores, so I'd rather team-up. Depending on how you see the roadmap for this project, I'd be happy to contribute interesting bits back or alternatively, we could develop T5 separately with the idea of porting back bits over time as lessons are learned and ideas for a .NET Core version are experimented/solidified there. Thoughts?


[morelinq]: https://morelinq.github.io/
[Fold.g.tt]: https://github.com/morelinq/MoreLINQ/blob/812045328654177044e67eb93212efa3a7de20a8/MoreLinq/ç.g.tt
[ToDelimitedString.g.tt]: https://github.com/morelinq/MoreLINQ/blob/812045328654177044e67eb93212efa3a7de20a8/MoreLinq/ToDelimitedString.g.tt

**Comment by mhutch** [comment]
I don't want to drop Mono/.NET support. However, I'd be very happy to merge .NET Core / .NET Standard support into this repo.

I'd also love to add additional support and features:

* generating .NET Standard-compatible precompiled templates
* dotnet cli tools packages (`dotnet tt`, maybe a global tools package)
* MSBuild targets packages that work on netcore and full framework
* file template nupkgs for tt files (`dotnet new t4 -precompiled` etc)
* a language server powered by the tt parser?
* maybe even evolve the t4 language?

I set up some infrastructure on this repo to kick things off:

- CLA bot is set up
- build & test on Mono is set up using Travis CI
- projects are ported to sdk-style projects, so we can use multitargeting
- there's a .editorconfig for consistent style
- nugets are packed with `msbuild /t:Pack`

**Comment by mhutch** [comment]
I filed / renamed a bunch of issues to track the various pieces:

[Support running on .NET Core](https://github.com/mono/t4/issues/6)
[Make precompiled templates compatible with .NET Standard](https://github.com/mono/t4/issues/13))
[Add dotnet tool package #10](https://github.com/mono/t4/issues/10)
[Add global dotnet tool package #11](https://github.com/mono/t4/issues/11)
[Add MSBuild targets package #12](https://github.com/mono/t4/issues/12)
[Add file template package for tt files](https://github.com/mono/t4/issues/14)
