### ISSUE TITLE
parameter property generate error CS0120

### ISSUE THREAD

**Issue by kccarter76** [mono/t4#88]
[CS0120](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0120)
[GeneratedTextTransformation.txt](https://github.com/mono/t4/files/5064624/GeneratedTextTransformation.txt)

after looking at the code that was generated it looks like the field and the property need to be declared static

**Comment by kccarter76** [comment]
I did try to implement them not being static and the engine was not able to reference the property. making the read only property static was the simplest solution to making it work.

**Comment by mhutch** [comment]
Unless I'm misreading something, the code appears to be trying to initialize a const string with a (variable) property value?

**Comment by kccarter76** [comment]
after everything was said and done. the following links are the working T4 templates.
https://github.com/SubSonic-Core/Extensions.VisualStudio/blob/master/SubSonic.Core.Template/Settings.ttinclude
https://github.com/SubSonic-Core/Extensions.VisualStudio/blob/master/SubSonic.Core.Template/SqlServer.ttinclude
https://github.com/SubSonic-Core/Extensions.VisualStudio/blob/master/SubSonic.Core.Template/SubSonicDataContext.stt
https://github.com/SubSonic-Core/Extensions.VisualStudio/blob/master/SubSonic.Core.Template/SubSonicDataModels.stt

the files them selves are used in a vsix template.

**Comment by mhutch** [comment]
I don't see any parameters in those templates though?

**Comment by kccarter76** [comment]
settings.ttinclude line 1.

the the vsix template replaces $connectionKey$ with a property name ,that is renamed in a identifiable way that can be compiled in code, to a connection in visual studio data explorer. the transformation host retrieves the connection string from visual studio and stores it as a parameter to be used. in the template.

**Comment by mhutch** [comment]
I see. So the pattern here is an include that adds a parameter to the template class, and then defines a nested static helper class that wants to access that parameter from the template class instance. The template class also has to be aware of this and initialize the settings class by assigning it the host value.

I can think of a few alternatives:
* instead of having a nested settings class with helper properties, have the include just add those helper properties directly to the template class
* create an instance of the settings class instance from the the template class e.g. `var settings = new Settings(Host, connectionString)`
* use a custom base class for the template

**Comment by kccarter76** [comment]
assuming, I am remembering the code correctly that sounds about right. what you are suggesting is in line with dependency injection pattern. That would solve the problem in a way that applicable for everyone. If I have the time to experiment I look into it. currently working on other projects that actually put bread on the table.

**Comment by mhutch** [comment]
Closing this for now as making these properties static would cause other problems and there are ways to structure a template so that the static properties are not needed.
