### ISSUE TITLE
How to Add Complex Parameters?

### ISSUE THREAD

**Issue by DuNuNuBatman** [mono/t4#98]
How do you add complex parameters to the TemplateGenerator? I see examples of strings and ints32's in the unit tests.

``` C#
var generator = new TemplateGenerator();
generator.AddParameter(null, null, "Model", new Model.Application()); // ???
```

```
<#@ template language="C#" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ parameter name="Model" type="Model.Application" #>
```

**Comment by mhutch** [comment]
This limitation is unfortunately an artifact of how templates resolve parameters from the host in the original VS hosting interfaces: due to `ITextTemplatingEngineHost.ResolveParameterValue`.

There are a couple other ways your templates could get parameters from the host.

You could use a custom host and set your templates as host specific. They will then be able to access members on the host. I've expanded out the examples in [TextTemplatingSessionTests](https://github.com/mono/t4/blob/master/Mono.TextTemplating.Tests/TextTemplatingSessionTests.cs#L61) - for example,  `TestCustomHostWithSpecificHostType` accesses data on a strongly typed host, and `TestCustomBaseClassWithSpecificHostType` does the same via a custom base class.

If you need the parameters to vary between files you could also use a custom directive processor. Parameters are already implemented as a directive processor.

I suppose it might be useful to have a way for the host to hook into template execution but that would need to be designed.

I'm curious why you're not using preprocessed/runtime templates. I know they don't work for all scenarios and sometimes it's necessary to use the engine directly, which is why I publish it on NuGet, but I don't have much insight into how it's used in practice.

**Comment by DuNuNuBatman** [comment]
I just started with the NuGet package as I was writing a console application to generate multiple files at once. What are the preprocessed/runtime templates? I guess I thought it is what I was doing but I just started learning T4 as a way to generate multiple types of text so I am ignorant to a lot of the tools and processes already out there.

For my project I was attempting to write a .net core console application so it could be used outside of the visual studio host.

Thanks for the direction with the custom host.

**Comment by mhutch** [comment]
[Runtime templates](https://docs.microsoft.com/en-us/visualstudio/modeling/run-time-text-generation-with-t4-text-templates?view=vs-2019) are where you use the T4 engine to generate class files from the tt files. They're great if you don't expect the tt files to change in your published app. You can then compile those classes into an app and use them however you want e.g. assign properties, call methods. You can also use partial classes to implement helper members in the template classes.

You can generate runtime template classes with the `-class=My.Class.Name` commandline argument.

**Comment by DuNuNuBatman** [comment]
Cool, thanks for the additional details. I'll dig into the t4 command line tool more.
