### ISSUE TITLE
Discontinued .NET Core 3.1 support in dotnet-t4?

### ISSUE THREAD

**Issue by anders9ustafsson** [mono/t4#99]
I have recently been using the dotnet-t4 2.2.0-preview packages from Github, but just now decided to try out the official 2.2.0 release on Nuget. However, while the preview packages ran on .NET Core 3.1, the official release only runs on .NET 5. Is there any particular reason for not providing 3.1 support any longer? In other case, could you consider to provide an updated Nuget package with 3.1 support?

**Comment by anders9ustafsson** [comment]
Dear @mhutch and other maintainers, it would be great to get your feedback on this.

**Comment by mhutch** [comment]
Sorry, I upgraded the global tool to `net5.0` because I wanted to allow templates to use .NET 5.0 APIs. I didn't even consider whether runtime roll-forward settings could be used with global tools or which would be appropriate.

I've gone with `LatestMajor` roll-forward as that gives access to .NET 5.0 APIs even though .NET 3.1 is present on my machine:

```bash
$ echo '<#= System.GC.GetGCMemoryInfo().Index #>' | dotnet-t4/bin/Debug/netcoreapp3.1/t4.exe -o -
0
```

**Comment by anders9ustafsson** [comment]
Many thanks for fixing this issue, @mhutch ! Will there be a 2.2.1 release on _nuget.org_ with the fix, or will the fix be included in the 2.3.0 release only?

**Comment by mhutch** [comment]
I just pushed 2.2.1 packages

**Comment by anders9ustafsson** [comment]
Works fine! Many thanks for the push, @mhutch !
